name: Linter

on:
  push:
    branches:
      - develop
      - main
      - feature/*

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run linter
        run: bash .github/scripts/linter.sh
